import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TansStackProvider from "@/components/providers/TansStackProvider";

export const metadata = {
  title: "AgroSuccour",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-Grey50">
        <TansStackProvider>
          <Header />
          {children}
          <Footer />
        </TansStackProvider>
      </body>
    </html>
  );
}
