"use client";
import "./globals.css";
import { usePathname } from "next/navigation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TansStackProvider from "@/components/providers/TansStackProvider";
import SessionProvider from "@/components/providers/SessionProvider";

// export const metadata = {
//   title: "AgroSuccour",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current path
  // List of paths where the footer should be hidden
  const hiddenFooterPaths = [
    "/checkout",
    "/payment",
    "/review",
    "/ordercompleted",
  ];

  return (
    <html lang="en">
      <body className="bg-Grey50">
        <SessionProvider>
          <TansStackProvider>
            <Header />
            {children}
            {!hiddenFooterPaths.includes(pathname) && <Footer />}
          </TansStackProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
